pipeline {
    agent any

    environment {
        IMAGE_NAME = "saurabh0010/mern-backend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Backend Repository') {
            steps {
                dir('app') {
                    git branch: 'main',
                        url: 'https://github.com/MiladJoodi/MERN_Stack_CRUD.git'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app/backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('app/backend') {
                    echo "Skipping tests"
                    // sh 'npm test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app/backend') {
                    sh '''
                    docker build -t $IMAGE_NAME:$IMAGE_TAG .
                    docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'DockerCreds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                    docker push $IMAGE_NAME:$IMAGE_TAG
                    docker push $IMAGE_NAME:latest

                    docker logout
                    '''
                }
            }
        }
    }
}
